version: '3'

services:
  expenses-app:
    image: expense-tracker
    build: .
    ports:
      - "3000:3000"
    volumes:
      - expenses-data:/usr/src/app/data

volumes:
  expenses-data:
    driver: local